[options]
girs_directories = [".", "gir-files"]
library = "Libosinfo"
version = "1.0"
min_cfg_version = "1.0"
target_path = "."
work_mode = "sys"
external_libraries = [
   "GLib",
   "GObject",
   "Gio",
]