[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "1.0"
gio-sys = "0.4.0"
glib-sys = "0.4.0"
gobject-sys = "0.4.0"
libc = "0.2"

[features]
dox = []

[lib]
name = "libosinfo_sys"

[package]
build = "build.rs"
links = "libosinfo"
name = "libosinfo-sys"
version = "0.2.0"
