// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::List;
use glib::{prelude::*, translate::*};
use std::fmt;

glib::wrapper! {
    #[doc(alias = "OsinfoDatamapList")]
    pub struct DatamapList(Object<ffi::OsinfoDatamapList, ffi::OsinfoDatamapListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_datamaplist_get_type(),
    }
}

impl DatamapList {
    pub const NONE: Option<&'static DatamapList> = None;

    #[doc(alias = "osinfo_datamaplist_new")]
    pub fn new() -> DatamapList {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::osinfo_datamaplist_new()) }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`DatamapList`] objects.
    ///
    /// This method returns an instance of [`DatamapListBuilder`](crate::builders::DatamapListBuilder) which can be used to create [`DatamapList`] objects.
    pub fn builder() -> DatamapListBuilder {
        DatamapListBuilder::new()
    }
}

impl Default for DatamapList {
    fn default() -> Self {
        Self::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`DatamapList`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DatamapListBuilder {
    builder: glib::object::ObjectBuilder<'static, DatamapList>,
}

impl DatamapListBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn element_type(self, element_type: glib::types::Type) -> Self {
        Self {
            builder: self.builder.property("element-type", element_type),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`DatamapList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DatamapList {
        self.builder.build()
    }
}

impl fmt::Display for DatamapList {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("DatamapList")
    }
}
