// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::List;
use glib::prelude::*;
#[cfg(feature = "v1_7")]
#[cfg_attr(docsrs, doc(cfg(feature = "v1_7")))]
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "OsinfoFirmwareList")]
    pub struct FirmwareList(Object<ffi::OsinfoFirmwareList, ffi::OsinfoFirmwareListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_firmwarelist_get_type(),
    }
}

impl FirmwareList {
    pub const NONE: Option<&'static FirmwareList> = None;

    #[cfg(feature = "v1_7")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_7")))]
    #[doc(alias = "osinfo_firmwarelist_new")]
    pub fn new() -> FirmwareList {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::osinfo_firmwarelist_new()) }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`FirmwareList`] objects.
    ///
    /// This method returns an instance of [`FirmwareListBuilder`](crate::builders::FirmwareListBuilder) which can be used to create [`FirmwareList`] objects.
    pub fn builder() -> FirmwareListBuilder {
        FirmwareListBuilder::new()
    }
}

#[cfg(feature = "v1_7")]
#[cfg_attr(docsrs, doc(cfg(feature = "v1_7")))]
impl Default for FirmwareList {
    fn default() -> Self {
        Self::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`FirmwareList`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct FirmwareListBuilder {
    builder: glib::object::ObjectBuilder<'static, FirmwareList>,
}

impl FirmwareListBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn element_type(self, element_type: glib::types::Type) -> Self {
        Self {
            builder: self.builder.property("element-type", element_type),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`FirmwareList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> FirmwareList {
        self.builder.build()
    }
}

impl fmt::Display for FirmwareList {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FirmwareList")
    }
}
