// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use crate::List;
use glib::{prelude::*, translate::*};
use std::fmt;

glib::wrapper! {
    #[doc(alias = "OsinfoInstallConfigParamList")]
    pub struct InstallConfigParamList(Object<ffi::OsinfoInstallConfigParamList, ffi::OsinfoInstallConfigParamListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_install_config_paramlist_get_type(),
    }
}

impl InstallConfigParamList {
    pub const NONE: Option<&'static InstallConfigParamList> = None;

    #[doc(alias = "osinfo_install_config_paramlist_new")]
    pub fn new() -> InstallConfigParamList {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::osinfo_install_config_paramlist_new()) }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`InstallConfigParamList`] objects.
    ///
    /// This method returns an instance of [`InstallConfigParamListBuilder`](crate::builders::InstallConfigParamListBuilder) which can be used to create [`InstallConfigParamList`] objects.
    pub fn builder() -> InstallConfigParamListBuilder {
        InstallConfigParamListBuilder::new()
    }
}

impl Default for InstallConfigParamList {
    fn default() -> Self {
        Self::new()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`InstallConfigParamList`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct InstallConfigParamListBuilder {
    builder: glib::object::ObjectBuilder<'static, InstallConfigParamList>,
}

impl InstallConfigParamListBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    pub fn element_type(self, element_type: glib::types::Type) -> Self {
        Self {
            builder: self.builder.property("element-type", element_type),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`InstallConfigParamList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> InstallConfigParamList {
        self.builder.build()
    }
}

impl fmt::Display for InstallConfigParamList {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("InstallConfigParamList")
    }
}
